### ISSUE TITLE
News | Week 5-11/8

### ISSUE THREAD

**Issue by Pnumek** [citizen-cosmos/SMM-Content#49]

**Comment by Pnumek** [comment]
KUJIRA $USK STABLECOIN LAUNCH — KICKSTARTING GROWN-UP DEFI
https://medium.com/team-kujira/kujira-usk-stablecoin-launch-kickstarting-grown-up-defi-26b4372d7aef

**Comment by Voskodan** [comment]
-  KUJIRA $USK Stablecoin Launch — kickstarting grown-up DeFI. Learn more here: https://medium.com/team-kujira/kujira-usk-stablecoin-launch-kickstarting-grown-up-defi-26b4372d7aef 
 -  The First Evmos Hackathon has finally started on Aug 11th! Join the official Q&A Group Chat to have your questions answered http://t.me/Evmoshackathon
- [@StaFi_Protocol](https://twitter.com/StaFi_Protocol) initially released #rATOM solution V1 on[ #StaFi](https://twitter.com/hashtag/StaFi?src=hashtag_click) chain. Now they are introducing #rATOM solution V2 on[ #StaFiHub](https://twitter.com/hashtag/StaFiHub?src=hashtag_click) due to the cross-chain issues between the[ #StaFi](https://twitter.com/hashtag/StaFi?src=hashtag_click) chain and [@cosmoshub](https://twitter.com/cosmoshub)     
- Biggest Movers: ATOM Climbs to Highest Point Since May, While SOL Rises by Over 10%

**Comment by Voskodan** [comment]
Didn't find much this week, if you know something else, will add it shortly
